# -*- coding: utf-8 -*-
"""Bollinger Band Code + Other possible formulas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpebUsJ0N75uGNkTvIyHQck00GRqSFGf
"""

import pandas as pd
import numpy as np
import math

#<<THIS WILL BE BASED ON THE ORGANIZED DATA FROM PANDAS>>

#//BOLLINGER BAND CALCULATION
#day_stat=amount of keywords for a particular day
#stat_num=day of specific stat (likely to be used for graphs)
#n=number of days (essentially a date)
#period=smoothing period(dependent on smoothing)
#m=number standard deviations (usually 2 and is constant)
#TKW=np.array[empty until data is collected] // typical keywords (based on keywords in a smoothing period)

#//BOLLINGER BAND
#ref_SMA=TKW.mean()
#bolu=ref_SMA+m*SD
#bold=ref_SMA-m*SD
#SD=np.std(TKW)

#//BOLLINGER BAND MONITOR
#if {the amount of days updates or smth, for example 'stat_num>n'}:
  #for i in range(n,n+1):  //I'm not exactly sure how to write a program that constantly monitors the data, so modify the code when necessary
    #TKW.append(day_stat)
    #if day_stat<=bolu or day_stat>=bold:
      #period=period+1
    #n=n+1